In [6]:
df = pd.read_csv(r"D:\true_car_project_full.csv")
df

<IPython.core.display.Javascript object>

Id  Price  Year  Mileage            City State  \
0              1  16472  2015    18681  Jefferson City    MO   
1              2  15749  2015    27592        Highland    IN   
2              3  16998  2015    13650           Boone    NC   
3              4  15777  2015    25195     New Orleans    LA   
4              5  16784  2015    22800       Las Vegas    NV   
...          ...    ...   ...      ...             ...   ...   
1048570  1048571  16995  2015    27095        Honolulu    HI   
1048571  1048572  20491  2014    77590        Franklin    WI   
1048572  1048573  19355  2014    34554     King George    VA   
1048573  1048574  17173  2014    61115          Conroe    TX   
1048574  1048575  18097  2014    40625           Macon    GA   

                City State                Vin    Make              Model  \
0        Jefferson City MO  KL4CJBSBXFB267643   Buick  EncoreConvenience   
1              Highland IN  KL4CJASB5FB245057   Buick          EncoreFWD   
2                 Boone NC  KL4CJCSB0FB264921   Buick      EncoreLeather   
3           New Orleans LA  KL4CJASB4FB217542   Buick          EncoreFWD   
4             Las Vegas NV  KL4CJBSB3FB166881   Buick  EncoreConvenience   
...                    ...                ...     ...                ...   
1048570        Honolulu HI  1N4AL3AP4FN388943  Nissan          Altima2.5   
1048571        Franklin WI  JN8AZ1MWXEW525865  Nissan          MuranoAWD   
1048572     King George VA  5N1AT2MV5EC838877  Nissan            RogueSL   
1048573          Conroe TX  5N1AR2MN5EC727938  Nissan        PathfinderS   
1048574           Macon GA  5N1AT2MV6EC819786  Nissan            RogueSV   

            Region  
0          Midwest  
1          Midwest  
2        Southeast  
3        Southeast  
4          Rockies  
...            ...  
1048570  Northeast  
1048571  Northeast  
1048572  Northeast  
1048573  Northeast  
1048574  Northeast  

[1048575 rows x 11 columns]

In [7]:
sum(df.Price.isnull())

0

In [8]:
df.Price.mean()

21067.250472307656

In [9]:
print(df['Price'].quantile(0.10))
print(df['Price'].quantile(0.90))

8998.0
35900.0


In [10]:
df["Price"] = np.where(df["Price"] <8998.0, 8998.0,df['Price'])
df["Price"] = np.where(df["Price"] >35900.0, 35900.0,df['Price'])
print(df['Price'].skew())

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0.5147236125716723


In [11]:
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

13649.0


In [12]:
outliers=((df.Price < (Q1 - 1.5 * IQR)) | (df.Price > (Q3 + 1.5 * IQR)))

In [13]:
print(outliers)

0          False
1          False
2          False
3          False
4          False
           ...  
1048570    False
1048571    False
1048572    False
1048573    False
1048574    False
Name: Price, Length: 1048575, dtype: bool


In [14]:
for i in df.columns:
    print(df[i].unique())

[      1       2       3 ... 1048573 1048574 1048575]
[16472. 15749. 16998. ... 22002. 25214. 24112.]
[2015 2016 2014 2017 2013 2006 2003 2007 2005 2012 2011 2004 2009 2008
 2001 2010 2018 2002 2000 1999 1997 1998]
[ 18681  27592  13650 ... 127061 194966 126132]
['Jefferson City' 'Highland' 'Boone' ... 'Northfield' 'Huntington Valley'
 'Winslow']
[' MO' ' IN' ' NC' ' LA' ' NV' ' NY' ' CA' ' AR' ' FL' ' AZ' ' KY' ' TN'
 ' MI' ' TX' ' PA' ' OK' ' NJ' ' MD' ' OH' ' GA' ' Va' ' Fl' ' CO' ' ND'
 ' AL' ' IL' ' MA' ' WA' ' WI' ' MN' ' VA' ' KS' ' RI' ' OR' ' MS' ' NM'
 ' SC' ' NE' ' IA' ' NH' ' UT' ' ME' ' CT' ' HI' ' ID' ' DE' ' MT' ' WV'
 ' WY' ' SD' ' AK' ' VT' ' Ga' ' ga' ' Md' ' Ca' ' Oh' ' Az' ' DC']
['Jefferson City MO' 'Highland IN' 'Boone NC' ... 'Fairfield NJ'
 'Columbus Oh' 'Winslow AZ']
['KL4CJBSBXFB267643' 'KL4CJASB5FB245057' 'KL4CJCSB0FB264921' ...
 '5N1AT2MV5EC838877' '5N1AR2MN5EC727938' '5N1AT2MV6EC819786']
['Buick' 'Acura' 'Alfa' 'Aston' 'Audi' 'Bentley' 'BMW' 'Cadillac'
 'Ch

In [15]:
def clean_data(df):

    le = LabelEncoder()
    df.Region = le.fit_transform(df.Region)
    df = pd.get_dummies(data = df, columns=["Region"], drop_first = False)
    df = df.sort_index(axis=1)
    return df

df = clean_data(df)
df

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

City         City State       Id    Make  Mileage  \
0        Jefferson City  Jefferson City MO        1   Buick    18681   
1              Highland        Highland IN        2   Buick    27592   
2                 Boone           Boone NC        3   Buick    13650   
3           New Orleans     New Orleans LA        4   Buick    25195   
4             Las Vegas       Las Vegas NV        5   Buick    22800   
...                 ...                ...      ...     ...      ...   
1048570        Honolulu        Honolulu HI  1048571  Nissan    27095   
1048571        Franklin        Franklin WI  1048572  Nissan    77590   
1048572     King George     King George VA  1048573  Nissan    34554   
1048573          Conroe          Conroe TX  1048574  Nissan    61115   
1048574           Macon           Macon GA  1048575  Nissan    40625   

                     Model    Price  Region_0  Region_1  Region_2  Region_3  \
0        EncoreConvenience  16472.0         1         0         0         0   
1                EncoreFWD  15749.0         1         0         0         0   
2            EncoreLeather  16998.0         0         0         0         0   
3                EncoreFWD  15777.0         0         0         0         0   
4        EncoreConvenience  16784.0         0         0         0         1   
...                    ...      ...       ...       ...       ...       ...   
1048570          Altima2.5  16995.0         0         1         0         0   
1048571          MuranoAWD  20491.0         0         1         0         0   
1048572            RogueSL  19355.0         0         1         0         0   
1048573        PathfinderS  17173.0         0         1         0         0   
1048574            RogueSV  18097.0         0         1         0         0   

         Region_4  Region_5 State                Vin  Year  
0               0         0    MO  KL4CJBSBXFB267643  2015  
1               0         0    IN  KL4CJASB5FB245057  2015  
2               1         0    NC  KL4CJCSB0FB264921  2015  
3               1         0    LA  KL4CJASB4FB217542  2015  
4               0         0    NV  KL4CJBSB3FB166881  2015  
...           ...       ...   ...                ...   ...  
1048570         0         0    HI  1N4AL3AP4FN388943  2015  
1048571         0         0    WI  JN8AZ1MWXEW525865  2014  
1048572         0         0    VA  5N1AT2MV5EC838877  2014  
1048573         0         0    TX  5N1AR2MN5EC727938  2014  
1048574         0         0    GA  5N1AT2MV6EC819786  2014  

[1048575 rows x 16 columns]